[project]
name = "stacks-microtask"
description = "A decentralized micro-task bounty board PoC"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.microtasks]
path = "contracts/microtasks.clar"
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false 